=== phobophobia/web2-backend/service/src/test/resources/schema.dtd
<!ELEMENT dataset (
    api_audit*,
    author*,
    author_url*,
    bookmark*,
    change_password*,
    comment*,
    contribution*,
    episode*,
    listener_stat*,
    mix*,
    radioshow*,
    role*,
    scheduling*,
    schema_version*,
    show_url*,
    tag*,
    tag_textcontent*,
    textcontent*,
    url*,
    user*)>

<!ELEMENT api_audit EMPTY>
<!ATTLIST api_audit
    id CDATA #REQUIRED
    user CDATA #REQUIRED
    url CDATA #REQUIRED
    postParams CDATA #REQUIRED
    callDate CDATA #REQUIRED
    method CDATA #REQUIRED
>

<!ELEMENT author EMPTY>
<!ATTLIST author
    id CDATA #REQUIRED
    user_id CDATA #IMPLIED
    name CDATA #REQUIRED
    alias CDATA #IMPLIED
    photo CDATA #REQUIRED
    avatar CDATA #REQUIRED
    introduction CDATA #REQUIRED
    email CDATA #IMPLIED
>

<!ELEMENT author_url EMPTY>
<!ATTLIST author_url
    author_id CDATA #REQUIRED
    url_id CDATA #REQUIRED
>

<!ELEMENT bookmark EMPTY>
<!ATTLIST bookmark
    id CDATA #REQUIRED
    radioshow_id CDATA #IMPLIED
    episode_id CDATA #IMPLIED
    user_id CDATA #IMPLIED
    start CDATA #REQUIRED
    end CDATA #REQUIRED
    title CDATA #REQUIRED
    content CDATA #IMPLIED
    full_episode CDATA #REQUIRED
    karma CDATA #IMPLIED
    selected CDATA #REQUIRED
>

<!ELEMENT change_password EMPTY>
<!ATTLIST change_password
    id CDATA #REQUIRED
    user_id CDATA #IMPLIED
    token CDATA #REQUIRED
    created CDATA #REQUIRED
>

<!ELEMENT comment EMPTY>
<!ATTLIST comment
    id CDATA #REQUIRED
    comment CDATA #REQUIRED
    created CDATA #IMPLIED
    moment CDATA #IMPLIED
    type CDATA #REQUIRED
    identifier CDATA #REQUIRED
    status CDATA #REQUIRED
    author_id CDATA #REQUIRED
    parent_id CDATA #IMPLIED
>

<!ELEMENT contribution EMPTY>
<!ATTLIST contribution
    id CDATA #REQUIRED
    radioshow_id CDATA #REQUIRED
    author_id CDATA #REQUIRED
    nick CDATA #REQUIRED
>

<!ELEMENT episode EMPTY>
<!ATTLIST episode
    id CDATA #REQUIRED
    radioshow_id CDATA #IMPLIED
    textcontent_id CDATA #IMPLIED
    plannedFrom CDATA #REQUIRED
    plannedTo CDATA #REQUIRED
    realFrom CDATA #REQUIRED
    realTo CDATA #REQUIRED
>

<!ELEMENT listener_stat EMPTY>
<!ATTLIST listener_stat
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    count CDATA #IMPLIED
    date CDATA #REQUIRED
>

<!ELEMENT mix EMPTY>
<!ATTLIST mix
    id CDATA #REQUIRED
    show_id CDATA #IMPLIED
    author CDATA #REQUIRED
    title CDATA #REQUIRED
    file CDATA #REQUIRED
    date CDATA #IMPLIED
    type CDATA #REQUIRED
    category CDATA #REQUIRED
    content CDATA #IMPLIED
>

<!ELEMENT radioshow EMPTY>
<!ATTLIST radioshow
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    definition CDATA #IMPLIED
    alias CDATA #IMPLIED
    banner CDATA #IMPLIED
    description CDATA #IMPLIED
    type CDATA #REQUIRED
    status CDATA #REQUIRED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
    id CDATA #REQUIRED
    parent_role_id CDATA #IMPLIED
    name CDATA #REQUIRED
>

<!ELEMENT scheduling EMPTY>
<!ATTLIST scheduling
    id CDATA #REQUIRED
    radioshow_id CDATA #IMPLIED
    weekType CDATA #REQUIRED
    base CDATA #REQUIRED
    weekDay CDATA #REQUIRED
    hourFrom CDATA #REQUIRED
    minFrom CDATA #REQUIRED
    duration CDATA #REQUIRED
    validFrom CDATA #REQUIRED
    validTo CDATA #REQUIRED
>

<!ELEMENT schema_version EMPTY>
<!ATTLIST schema_version
    version_rank CDATA #REQUIRED
    installed_rank CDATA #REQUIRED
    version CDATA #REQUIRED
    description CDATA #REQUIRED
    type CDATA #REQUIRED
    script CDATA #REQUIRED
    checksum CDATA #IMPLIED
    installed_by CDATA #REQUIRED
    installed_on CDATA #IMPLIED
    execution_time CDATA #REQUIRED
    success CDATA #REQUIRED
>

<!ELEMENT show_url EMPTY>
<!ATTLIST show_url
    radioshow_id CDATA #REQUIRED
    url_id CDATA #REQUIRED
>

<!ELEMENT tag EMPTY>
<!ATTLIST tag
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>

<!ELEMENT tag_textcontent EMPTY>
<!ATTLIST tag_textcontent
    textcontent_id CDATA #REQUIRED
    tag_id CDATA #REQUIRED
>

<!ELEMENT textcontent EMPTY>
<!ATTLIST textcontent
    id CDATA #REQUIRED
    title CDATA #REQUIRED
    type CDATA #REQUIRED
    format CDATA #REQUIRED
    content CDATA #IMPLIED
    created CDATA #IMPLIED
    modified CDATA #IMPLIED
    author CDATA #IMPLIED
    alias CDATA #IMPLIED
>

<!ELEMENT url EMPTY>
<!ATTLIST url
    id CDATA #REQUIRED
    url CDATA #REQUIRED
    type CDATA #IMPLIED
>

<!ELEMENT user EMPTY>
<!ATTLIST user
    id CDATA #REQUIRED
    role_id CDATA #IMPLIED
    username CDATA #REQUIRED
    password CDATA #IMPLIED
    email CDATA #REQUIRED
    salt CDATA #IMPLIED
    role CDATA #IMPLIED
>

=== phobophobia/web2-backend/service/src/test/resources/hu/tilos/radio/backend/baseData.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/schema.dtd">
<dataset>
    <author id="1" name="AUTHOR1" photo="asd" avatar="avatar/asd.jpg" introduction="nothing"></author>
    <author id="2" name="AUTHOR2" photo="asd" avatar="asd" introduction="nothing"></author>
    <url id="1" url="http://szabi.hu"></url>
    <url id="2" url="http://show1.com"></url>
    <author_url author_id="1" url_id="1"></author_url>

    <textcontent id="1" title="tamogatas" type="page" format="legacy" content="asd" author="asd" alias="asd"
                 created="2012-12-12 12:12:12" modified="2012-12-12 12:12:12"></textcontent>

    <textcontent id="2" title="Jo musor" type="episode" format="legacy" content="fasza am" author="asd" alias="asd"
                 created="2012-12-12 12:12:12" modified="2012-12-12 12:12:12"></textcontent>

    <radioshow id="1" name="3. utas" alias="3utas" description="a potyoutasok műsora" type="0" status="1"></radioshow>
    <radioshow id="2" name="Haza és Haladás" alias="hazaeshaladas" description="h%h" type="0" status="1"></radioshow>
    <radioshow id="3" name="Vendéglő a világ végén" alias="vendeglo" description="mindenkiboldog" type="0"
               status="1"></radioshow>
    <show_url radioshow_id="1" url_id="2"></show_url>

    <contribution id="1" nick="bela" author_id="1" radioshow_id="1"></contribution>
    <contribution id="2" nick="bela" author_id="2" radioshow_id="1"></contribution>

    <episode id="2"
             radioshow_id="1"
             textcontent_id="2"
             plannedFrom="2014-04-11 08:00:00"
             plannedTo="2014-04-11 10:00:00"
             realFrom="2014-04-11 08:00:00"
             realTo="2014-04-11 10:00:00"
            ></episode>

    <episode id="1" radioshow_id="1" plannedFrom="2014-04-04 08:00:00" plannedTo="2014-04-04 10:00:00"
             realTo="2014-04-04 10:00:00" realFrom="2014-04-04 08:00:00"></episode>



    <scheduling id="1" validFrom="2014-04-15 10:00:00" validTo="2014-06-10 10:00:00" hourFrom="8" minFrom="0"
                duration="120"
                weekType="1" base="2014-04-15 10:00:00" weekDay="5" radioshow_id="1"></scheduling>

    <scheduling id="2" validFrom="2014-04-15 10:00:00" validTo="2014-06-10 10:00:00" hourFrom="8" minFrom="0"
                duration="120"
                weekType="2"
                base="2014-04-15 10:00:00"
                weekDay="5"
                radioshow_id="3"></scheduling>

    <bookmark id="1" start="2014-04-04 08:13:00" end="2014-04-04 10:13:00"
              title="Jo kis beszelgetes 1" content="x1" episode_id="1" selected="1" full_episode="0"
              karma="0"></bookmark>
    <bookmark id="2" start="2014-04-04 08:13:00" end="2014-04-04 10:13:00"
              title="Jo kis beszelgetes 2" content="x2" episode_id="1" radioshow_id="1" selected="0" full_episode="0"
              karma="0"></bookmark>

    <mix id="1" type="1" author="asd" title="good mix" file="asd.mp3" date="2013-04-05" show_id="1" category="2"></mix>
    <mix id="3" type="1" author="asd" title="good mix2" file="asd2.mp3" date="2013-04-05" show_id="1"
         category="1"></mix>
    <mix id="2" type="1" author="asd" title="good mix2" file="asd2.mp3" category="1"></mix>
    <tag id="1" name="kukac" type="0"></tag>
    <tag id="2" name="asd" type="0"></tag>
    <tag id="3" name="harom" type="0"></tag>
    <tag_textcontent textcontent_id="1" tag_id="1"></tag_textcontent>
    <tag_textcontent textcontent_id="2" tag_id="1"></tag_textcontent>
    <tag_textcontent textcontent_id="2" tag_id="3"></tag_textcontent>
    <tag_textcontent textcontent_id="1" tag_id="2"></tag_textcontent>



    <role id="3" name="author"></role>
    <user id="1" role_id="3" username="bela" email="bela@bela.hu" password="22679322a29a62da3c2558eac2ec5fe3d055db61"
          salt="d25541250d47c49f20b5243f95dbbd91e4db3d0d"></user>

    <change_password id="1" token="sadasd" created="2009-12-12 12:23:00" user_id="1"></change_password>


    <comment id="1" comment="mi ez a fos zene" type="0" identifier="1" status="1" author_id="1"></comment>
    <comment id="2" comment="mi ez a fos zene2" type="0" identifier="1" status="1" author_id="1"></comment>
    <comment id="3" comment="mi ez a fos zene3" parent_id="2" type="0" identifier="1" status="0" author_id="1"></comment>

</dataset>
